### ISSUE TITLE
add easily probable ground power pads

### ISSUE THREAD

**Issue by mattvenn** [omerk/caravel-breakout#1]
or use something like microbit. could put these on the motherboard too / instead

**Comment by omerk** [comment]
With long headers poking through the "pass through", connectors probing individual signals should be fairly easy already but I'll see if we can add an easy-to-clip-to-scope-ground exposed ground pad like the TI devboards:

![image](https://user-images.githubusercontent.com/9847/210182126-120f3888-6246-4a87-9000-8ceea0abc621.png)

And ditto: it might not be a bad idea to have some easy to poke/clip test points on the demo board too. I'll add an issue on that repo.

**Comment by omerk** [comment]
Closing this as we've moved this on to the main board.
